### ISSUE TITLE
.

### ISSUE THREAD

**Issue by uber97** [LesBoloss-es/weechat-signal-ocaml#1]

**Comment by Kerl13** [comment]
Nope, if I understand correctly, `signald-go` is a go library for interacting with signald.
I wanted a plugin in pure OCaml so I kinda have to rewrite my own library. In fact, the `src/lib` directory in this repository is meant to become a `signald-ocaml` library at some point, but this is still rather primitive right now. Once it is a little more mature, it will eventually become its own repository.

**Comment by Kerl13** [comment]
Just to clarify: this plugin makes use of [signald](https://gitlab.com/thefinn93/signald) though, directly via the unix socket.
